"""Generate the three disjoint W-12 SearXNG settings profiles."""

from __future__ import annotations

import copy
from pathlib import Path
from typing import Any

import yaml

from hyperion.infra.paths import project_root, searxng_settings_file
from hyperion.infra.services import SEARXNG_REPLICAS


def build_profiles(base: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Derive isolated profiles from one base document and replica registry."""
    declared = {str(engine["name"]): engine for engine in base.get("engines", [])}
    assigned: set[str] = set()
    profiles: dict[str, dict[str, Any]] = {}

    for db_index, replica in enumerate(SEARXNG_REPLICAS):
        overlap = assigned.intersection(replica.engines)
        if overlap:
            raise ValueError(f"engines assigned to multiple profiles: {sorted(overlap)}")
        missing = set(replica.engines) - declared.keys()
        if missing:
            raise ValueError(f"profile {replica.profile} has unknown engines: {sorted(missing)}")
        assigned.update(replica.engines)

        profile = copy.deepcopy(base)
        profile["general"]["instance_name"] = f"HYPERION {replica.profile.title()} Search"
        profile["server"]["secret_key"] = f"${{SEARXNG_{replica.profile.upper()}_SECRET}}"
        profile["valkey"] = {"url": f"redis://valkey:6379/{db_index}"}
        profile["engines"] = [copy.deepcopy(declared[name]) for name in replica.engines]
        profiles[replica.profile] = profile

    extras = declared.keys() - assigned
    if extras:
        raise ValueError(f"base engines are not assigned to a profile: {sorted(extras)}")
    return profiles


def generate_profiles(root: Path | None = None) -> list[Path]:
    """Write deterministic generated profiles and return their paths."""
    root = root or project_root()
    with searxng_settings_file().open(encoding="utf-8") as handle:
        base = yaml.safe_load(handle)
    outputs: list[Path] = []
    for name, profile in build_profiles(base).items():
        path = root / f"searxng_settings.{name}.yml"
        path.write_text(
            "# GENERATED by hyperion.infra.searxng_profiles; do not hand edit.\n"
            + yaml.safe_dump(profile, sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
        outputs.append(path)
    return outputs


if __name__ == "__main__":
    for generated in generate_profiles():
        print(generated)
