"""Generate the three disjoint W-12 SearXNG settings profiles.

Egress & capacity decision (overhaul §6 P1.4, recorded 2026-08-10):

    The operator chose to harden the existing stack rather than add a
    third-party keyed search API. This is the written decision record:

    * SearXNG remains the corpus. General web is served by the web replica's
      ``mwmbl`` + ``brave`` engines only, behind the engine-health circuit
      (P1.2: ``mojeek``/``yep`` are disabled — they 403 categorically from
      this datacenter/VPS egress). Scholar/reference API engines (crossref,
      openalex, wikipedia, ...) remain the fan-out rescue path for a dead
      web pool.
    * Egress is the single loopback replica set (Docker bridge, one host
      IP). No rotating proxy is used. That is a deliberate, documented
      trade: bans are absorbed by the engine-health cooldown (capped at 4h)
      and the boot-time TTL sweep, never by adding more anonymous scrapers.
    * If upstream bans return to catastrophic levels, the capacity answer is
      a keyed API or different egress — never more scraper engines or
      higher retry/timeout budgets (overhaul §9 anti-patterns 1-2).
"""

from __future__ import annotations

import copy
from pathlib import Path
from typing import Any

import yaml

from hyperion.infra.paths import project_root, searxng_settings_file
from hyperion.infra.services import SEARXNG_REPLICAS


def build_profiles(base: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Derive isolated profiles from one base document and replica registry."""
    declared = {str(engine["name"]): engine for engine in base.get("engines", [])}
    assigned: set[str] = set()
    profiles: dict[str, dict[str, Any]] = {}

    for db_index, replica in enumerate(SEARXNG_REPLICAS):
        overlap = assigned.intersection(replica.engines)
        if overlap:
            raise ValueError(f"engines assigned to multiple profiles: {sorted(overlap)}")
        missing = set(replica.engines) - declared.keys()
        if missing:
            raise ValueError(f"profile {replica.profile} has unknown engines: {sorted(missing)}")
        assigned.update(replica.engines)

        profile = copy.deepcopy(base)
        profile["use_default_settings"]["engines"]["keep_only"] = list(replica.engines)
        profile["general"]["instance_name"] = f"HYPERION {replica.profile.title()} Search"
        # Every container receives a different SEARXNG_SECRET value from its
        # ContainerSpec; the settings placeholder itself uses the official
        # entrypoint variable name shared by all profiles.
        profile["server"]["secret_key"] = "${SEARXNG_SECRET}"
        profile["valkey"] = {"url": f"valkey://valkey:6379/{db_index}"}
        profile["engines"] = [copy.deepcopy(declared[name]) for name in replica.engines]
        profiles[replica.profile] = profile

    extras = declared.keys() - assigned
    if extras:
        raise ValueError(f"base engines are not assigned to a profile: {sorted(extras)}")
    return profiles


def generate_profiles(root: Path | None = None) -> list[Path]:
    """Write deterministic generated profiles and return their paths."""
    root = root or project_root()
    with searxng_settings_file().open(encoding="utf-8") as handle:
        base = yaml.safe_load(handle)
    outputs: list[Path] = []
    for name, profile in build_profiles(base).items():
        path = root / f"searxng_settings.{name}.yml"
        path.write_text(
            "# GENERATED by hyperion.infra.searxng_profiles; do not hand edit.\n"
            + yaml.safe_dump(profile, sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
        outputs.append(path)
    return outputs


if __name__ == "__main__":
    for generated in generate_profiles():
        print(generated)
